create TABLE users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   email VARCHAR(255) NOT NULL,
   password VARCHAR(255) NOT NULL,
   username VARCHAR(255) NOT NULL,
   CONSTRAINT users_pkey PRIMARY KEY (id)
);

alter table users add CONSTRAINT uni_email UNIQUE (email);
alter table users add CONSTRAINT uni_username UNIQUE (username);

create TABLE roles (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   name VARCHAR(255),
   CONSTRAINT roles_pkey PRIMARY KEY (id)
);

create TABLE user_roles (
   user_id BIGINT NOT NULL,
   role_id BIGINT NOT NULL,
   CONSTRAINT user_roles_pkey PRIMARY KEY (user_id, role_id)
);

alter table user_roles add CONSTRAINT FK7ov27fyo7ebsvada1ej7qkphl FOREIGN KEY (user_id) REFERENCES users (id) ON update NO ACTION ON delete NO ACTION;
alter table user_roles add CONSTRAINT FKej3jidxlte0r8flpavhiso3g6 FOREIGN KEY (role_id) REFERENCES roles (id) ON update NO ACTION ON delete NO ACTION;

create TABLE authors (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   first_name VARCHAR(255) NOT NULL,
   last_name VARCHAR(255) NOT NULL,
   description VARCHAR(500) NOT NULL,
   CONSTRAINT authors_pkey PRIMARY KEY (id)
);

create TABLE books (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   description VARCHAR(500),
   title VARCHAR(255) NOT NULL,
   author_id BIGINT NOT NULL,
   CONSTRAINT books_pkey PRIMARY KEY (id)
);

alter table books add CONSTRAINT FK9rceatmdmh8w7ofovg6qwwu8s FOREIGN KEY (author_id) REFERENCES authors (id) ON update NO ACTION ON delete NO ACTION;